### ISSUE TITLE
Support for multiple fast-glob patterns when using cli

### ISSUE THREAD

**Issue by wouterroos** [axa-group/arm-template-merge#12]
## Summary

Add the possibility to supply multiple fast-glob patterns when calling arm-template-merge so template files from multiple folders can be retrieved.

## Desired solution

`call arm-template-merge **\*.template.json ..\..\..\SomeFolder\**\*.template.json my.template.json`

**Comment by poveden** [comment]
This is already supported:

```sh
arm-template-merge <input-template-pattern>... <output-template>
```
Perhaps the ellipsis is too inconspicuous. 😛

**Comment by wouterroos** [comment]
Huh, could've sworn that I couln't get it to work, but I just verified that it does. Thanks for clearing that up! 😛
