### ISSUE TITLE
Update documentation for use it with NPX

### ISSUE THREAD

**Issue by aldodfm** [axa-group/arm-template-merge#8]
## Summary

How to use arm-template-merge standalone.

## Desired solution

Command to execute in ARM template folders and generate full template

`npx arm-template-merge templates/*.json template.json`

**Comment by nulltoken** [comment]
@aldodfm Great idea! How would you feel about sending a Pull Request with the proposed modification to the `README.md` file?

**Comment by poveden** [comment]
Added in #11
